# Site settings
title: Adventures in cryptocurrency
email: daniel.tao@gmail.com
description: Musings of a neophyte hoping to learn more
url: http://danieltao.com
twitter_username: dan_tao
github_username: dtao
google_analytics: UA-42171040-3

# Comments
disqus:
  shortname: adventuresincryptocurrency

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
